//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id_ticket { get; set; }
        public int nom_quetion_in_ticket { get; set; }
        public Nullable<int> id_question { get; set; }
        public Nullable<int> nom_komplect { get; set; }
    
        public virtual Komplect_tickets Komplect_tickets { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
